@startuml database
hide circle
hide empty members
skinparam monochrome true
skinparam style strictuml
skinparam shadowing false
skinparam backgroundColor transparent
skinparam classBackgroundColor transparent

entity code_smell_lifespans {
  *id UUID <<PK>>
  *kind TEXT
  *repository TEXT
  *analysis UUID <<FK>>
}

entity code_smells {
  *id INTEGER <<PK>>
  *kind TEXT
  *lifespan UUID <<FK>>
  *ordinal INTEGER
  *repository TEXT
  *commit TEXT
  *locations JSONB
  message TEXT
}

code_smell_lifespans ||-|{ code_smells

entity analyses {
  *id UUID <<PK>>
  *name TEXT
}
analyses ||--o{ code_smell_lifespans

entity analyzed_commits {
  *analysis UUID
  *repository TEXT
  *commit TEXT
}

analyses ||-o{ analyzed_commits

@enduml
